services:
  gochat:
    build: .
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      - PORT=${PORT:-4545}
      - MODE=${MODE:-}
      - BOOTNODE=${BOOTNODE:-}
      - ROOM=${ROOM:-}
      - LISTEN=${LISTEN:-}
    ports:
      - "${PORT}:${PORT}/udp"
    entrypoint: >
      ./gochat
      {% if MODE %}
      --mode ${MODE}
      {% endif MODE %}
      {% if BOOTNODE %}
      --bootnode ${BOOTNODE}
      {% endif BOOTNODE %}
      {% if ROOM %}
      --room ${ROOM}
      {% endif ROOM %}
      {% if LISTEN %}
      --listen ${LISTEN}
      {% endif LISTEN %}